---
- name: Install icarus verilog
  hosts: all
  become: yes

  tasks:
  - apt_repository:
      repo: ppa:team-electronics/ppa
      state: present
      filename: icarus_verilog

  - name: Install icarus
    apt: name=verilog state=latest install_recommends=yes update_cache=yes

  - name: Install GTK wave
    apt: name=gtkwave state=latest install_recommends=yes update_cache=yes

