---
- name: Install pip
  hosts: all
  become: yes

  tasks:
  - name: Install pip
    apt: name=python3-pip state=latest install_recommends=yes update_cache=yes

  - name: install python packages
    pip:
      name:
      - numpy
      - matplotlib
      - pandas
      - scipy
      state: latest
      executable: pip3

