---
- name: Install octave
  hosts: all
  become: yes

  tasks:
  - apt_repository:
      repo: "ppa:gapost/octave"
    become: yes
    environment:
      APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1

  - name: Install octave
    apt: name=octave state=latest install_recommends=yes update_cache=yes

