# Install UHD, RFNOC, GNURADIO by pybombs
# https://kb.ettus.com/Getting_Started_with_RFNoC_Development
# https://files.ettus.com/manual/page_build_guide.html
# https://github.com/gnuradio/pybombs/issues/495

---
- name: Getting_Started_with_RFNoC_Development
  hosts: all
  become: no

  tasks:

  - name: Remove obsolete uhd packages
    become: yes
    apt:
      pkg:
        - libuhd*
        - uhd*
      state: absent
      autoremove: yes


  - name: Install pip and neccessary apt packages
    become: yes
    apt: 
      pkg:
        - libboost-all-dev
        - libusb-1.0-0-dev
        - doxygen
        - git
        - python3-docutils
        - python3-mako
        - python3-numpy
        - python3-requests
        - python3-ruamel.yaml
        - python3-setuptools
        - python3-dev
        - python3-pip
        - python3-aiohttp-mako
        - python-cheetah
        - cmake
        - build-essential
      state: latest
      install_recommends: yes
      update_cache: yes

  - name: install pybombs pip packages
    become: yes
    pip:
      name:
        - pybombs
      state: latest
      executable: pip3

  - name: Create folder
    become: yes
    file:
      path: /opt/pybombs-prefix
      state: directory
      owner: tcsadmin
      group: tcsadmin
      mode: '755'


  - name: run pybombs install
    shell: |
      #python3 -m pip install git+https://github.com/gnuradio/pybombs.git
      pybombs -y prefix init /opt/pybombs-prefix/rfnoc -a rfnoc-prefix
      pybombs -y -p rfnoc-prefix recipes add ettus git+https://github.com/EttusResearch/ettus-pybombs.git
      pybombs -y -p rfnoc-prefix recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git


  - name: Correct rfnoc recipe to UHD3.15.LTS+GNURADIO3.8
    template:
      backup: yes
      src: rfnoc.lwr
      dest: /opt/pybombs-prefix/rfnoc/.pybombs/recipes/ettus
      mode: '755'

  - name: build and install RFNOC+UHD+GNURADIO
    shell:  pybombs -y prefix init /opt/pybombs-prefix/rfnoc -a rfnoc-prefix -R rfnoc

  - name: Check installation and download FPGA images
    shell: |
      source /opt/pybombs-prefix/rfnoc/setup_env.sh
      uhd_config_info --version
      uhd_images_downloader
    args:
      executable: /bin/bash

