---
- name: Configure linux general tools
  hosts: all
  become: yes

  tasks:
  - name: Save proxy ENV variables to profile.d
    template:
      src: set_proxy.sh.j2
      dest: /etc/profile.d/set_proxy.sh
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Set sources list
    copy:
      src: templates/sources.list
      dest: /etc/apt/sources.list
      backup: yes
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Configure apt proxy
    template:
      src: 80proxy.j2
      dest: /etc/apt/apt.conf.d/80proxy
      owner: root
      group: root
      mode: '0644'

  - name: Install linux tools
    apt:
      name: "{{ item }}"
      state: latest
      install_recommends: yes
      update_cache: yes
    with_items:
      - htop
      - neovim
      - curl

  - name: Create student user
    user:
      name: "{{ student_username }}"
      password: "{{ student_password }}"

