---
- name: Reboot machines to windows system
  hosts: all
  become: yes
  tasks:

  - name: Select windows to next boot in grub menu...
    shell: grub-reboot 2
  - name: Rebooting...
    shell: shutdown -r -f -t 5

