---
- name: Install debs required by Xilinx 
  hosts: all
  become: yes
  tasks:

  - name: Install debs...
    become: yes
    apt:
      pkg:
        - libxm4
        - gitk
        - git-gui
        - libusb-dev
        - build-essential
        - libc6-dev-i386
        - fxload
        - libftdi-dev
      state: latest
      install_recommends: yes
      update_cache: yes


  - name: Install cable drivers from installed Xilinx ISE
    become: yes
    shell: ./setup_pcusb /opt/Xilinx/14.7/ISE_DS/ISE/
    args:
      chdir: /opt/Xilinx/usb-driver


