---
- name: Install xrdp (Linux RDP server)
  hosts: all
  tasks:

#  - name: Unzip script installing XRDP
#    become: yes
#    unarchive: 
#      remote_src: yes
#      src: https://www.c-nergy.be/downloads/xrdp-installer-1.2.zip
#      dest: /tmp
#      mode: a+rx

  - name: Copy modified script
    become: yes
    template:
      src: xrdp-installer-1.2.sh
      dest: /tmp/xrdp-installer-1.2.sh
      mode: a+rx

  - name: Run script to remove previous installation XRDP
    become: yes
    shell: /tmp/xrdp-installer-1.2.sh -r
    register: xrdp_remove_script_output
    args:
      chdir: /tmp

  - name: Debug Print a variable xrdp uninstall
    debug:
      msg: "{{ xrdp_remove_script_output.stdout }}"

  - name: Delete /etc/xrdp folder for clean install
    become: yes
    file:
      state: absent
      path: /etc/xrdp/

  - name: Run script installing XRDP
    become: yes
    shell: /tmp/xrdp-installer-1.2.sh -c -l -s
    register: xrdp_install_script_output
    args:
      chdir: /tmp
      creates:
        - /etc/xrdp/xrdp.ini
    

  - name: Debug Print a variable xrdp install
    debug:
#        msg: "The found path is {{ dev_sda_path.stdout | regex_replace('^\\(\\/dev\\/sda[0-9]*\\)', '\\1')  }}"
      msg: "{{ xrdp_install_script_output.stdout }}"

  - name: Correct startwm.sh(1) to fix desktop issue 
    become: yes
    template:
      backup: yes
      src: startwm.sh
      dest: /etc/xrdp/startwm.sh
      mode: '755'
      



